on:
  push:
    branches:
      - '**'
name: Serverless deploy personal env
jobs:
  deploy:
    name: personal deploy
    runs-on: ubuntu-latest
    steps:
    - name: "Hello world when it's Monday"
      shell: bash
      if: ${{ github.ref == '*-dev'}}
      run: |
          echo "branch_name="$(echo ${GITHUB_REF#refs/heads/} | sed '.*(?=\-))"" >> $GITHUB_ENV
    - name: serverless deploy
      if: ${{env.branch_name == '*-dev' }}
      uses: everafterai/github-action@master
      with:
        args: ${{ env.branch_name }}
  
      
