on:
  push:
    branches:
      - main
name: Serverless deploy personal env
jobs:
  deploy:
    name: personal deploy
    runs-on: ubuntu-latest
    steps:
    - name: "Hello world when it's Monday"
      shell: bash
      run: |
          echo "branch_name="$(echo ${GITHUB_REF#refs/heads/})"" >> $GITHUB_ENV
    - name: "Hello world when it's Monday"
      if: ${{ env.branch_name == *"-dev"*  }}
      run: |
          echo ${{ env.branch_name }} | sed '.*(?=\-)'
    - name: serverless deploy
      uses: everafterai/github-action@master
      with:
        args: ${{ env.branch_name }}
  
      
