on:
  push:
    branches:
      - test
name: Serverless deploy personal env
jobs:
  deploy:
    name: personal deploy
    runs-on: ubuntu-latest
    steps:
    - name: serverless deploy
      uses: everafterai/github-action@master
      with:
        args: ${{echo maor}}
