on:
  push:
    branches:
      - main
name: Serverless deploy personal env
jobs:
  deploy:
    name: personal deploy
    runs-on: ubuntu-latest
    steps:
    - name: "Hello world when it's Monday"
      run: |
          echo "action_state=yellow" >> $GITHUB_ENV
    - name: serverless deploy
      uses: everafterai/github-action@master
      with:
        args: ${{ env.action_state }}
  
      
