on:
  push:
    branches:
      - '**'
name: Serverless deploy personal env
jobs:
  deploy:
    name: personal deploy
    runs-on: ubuntu-latest
    steps:

    - name: "Hello world when it's Monday"
      shell: bash
      if: contains(github.ref, '-dev')
      run: |
          "branch_name"="$(echo ${GITHUB_REF#refs/heads/} | sed 's/.\{4\}$//')" >> $GITHUB_ENV 
          
    - name: serverless deploy
      if: contains(github.ref, '-dev')
      uses: everafterai/github-action@master
      with:
        args: ${{ env.branch_name }}
  
      
